### ISSUE TITLE
docs url needs updating

### ISSUE THREAD

**Issue by cjw296** [conda-forge/testfixtures-feedstock#7]
Hi,

I'm the author of testfixtures, I'm also a conda user so happy to help with this where I can.
The docs url should point to readthedocs now. I see Chris Barker fixed this a while back but it appears to have reverted back to the old url.

In specific, how do we fix this?
In general, how can I help?

Chris

**Comment by ChrisBarker-NOAA** [comment]
In specific, I'll update it now.

In general, you can submit a PR yourself in the future.

**Comment by ChrisBarker-NOAA** [comment]
OK -- just took a look and it's correct in the recipe.

and it's correct here:

https://anaconda.org/conda-forge/testfixtures

where is it wrong?

Also, would you like to be added as a feedstock maintainer? Then you could push updates yourself.

**Comment by cjw296** [comment]
https://anaconda.org/conda-forge/testfixtures - "home" is wrong, should be rtd.

Happy to become a maintainer if that works, might still need to PR until I know what I'm doing...

**Comment by ChrisBarker-NOAA** [comment]
got it -- I've updated the recipe, though I'm not sure when/how it will get updated on Anaconda.org.

**Comment by ChrisBarker-NOAA** [comment]
hmm -- new package built, but the urls on the Anaconda page haven't changed.

I'll see if I can find out how to update that.

**Comment by ChrisBarker-NOAA** [comment]
OK -- I think I finally learned how to re-render the feedstock (#8), which should update the urls, etc.

For the record, this is how you do it:

https://conda-forge.org/docs/webservice.html#conda-forge-admin-please-rerender

**Comment by cjw296** [comment]
All looks good!
